version: "2"
services:
  home:
    image: omelhoro1/homepage-next
    container_name: home-next
    restart: unless-stopped
    labels:
      - traefik.frontend.rule=Host:home.fischerops.com,software-unchained.com,home.software-unchained.com
      - traefik.enable=true
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
